# Generated by Django 2.2.5 on 2022-01-18 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thirdapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jejuolle',
            table='jeju_olle',
        ),
    ]
