# Generated by Django 2.2.5 on 2022-01-18 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0002_armyshop'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='armyshop',
            table='army_shop',
        ),
    ]
